databases:
  - name: vcyou_db
    plan: free
    databaseName: vcyou
    user: vcyou_user

services:
  - type: web
    plan: free
    name: vcyou
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd $RENDER_PROJECT_DIR && gunicorn --chdir $RENDER_PROJECT_DIR vcyou.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vcyou_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: DJANGO_SETTINGS_MODULE
        value: vcyou.settings
      - key: PYTHONPATH
        value: $RENDER_PROJECT_DIR